Repository chinese-board-games/luzhanqi-web, pull requests merged in 2023-11, with the labels that each got.

#91 Rs/mobile ux fixes
  .prettierrc.json
  package-lock.json
  package.json
  public/logged-in.png
  src/CustomFonts.js
  src/components/AuthModal/AuthModal.js
  src/components/BoardSetup/HalfBoard.js
  src/components/BoardSetup/index.js
  src/components/DragablePiece.js
  src/components/GameBoard/FrontLines.js
  src/components/GameBoard/Mountain.js
  src/components/GameBoard/index.js
  src/components/GameOver/GameOver.js
  src/components/LZQ/LZQ.js
  src/components/Lobby/Lobby.js
  src/components/Login/CreateAccount.js
  src/components/Login/Phone.js
  src/components/Login/SignIn.js
  src/components/NavBar/NavBar.js
  src/components/Piece/index.js
  src/components/Position.js
  src/components/SelectablePosition.js
  src/components/Setup/Setup.js
  src/components/SortablePiece.js
  src/components/UserModal/UserModal.js
  src/contexts/FirebaseContext.js
  src/contexts/GameContext.js
  src/index.js
  src/models/Piece/Piece.js
  src/theme.js
  src/utils/core.js
  src/utils/getSuccessors.js
  src/utils/index.js
  src/views/Debug.js
  src/views/Game.js
  src/views/Menu.js
Labels: bug, frontend

#94 Gameid leave game
  src/api/Game.js
  src/components/Lobby/Lobby.js
  src/components/UserModal/UserModal.js
  src/contexts/GameContext.js
  src/views/Game.js
  src/views/Menu.js
Labels: bug, frontend, feature, MVP

#101 Update Game with Firebase uid when logging in after game start
  src/api/Game.js
  src/api/User.js
  src/components/AuthModal/AuthModal.js
  src/components/Login/CreateAccount.js
  src/components/Login/Google.js
  src/components/Login/Login.js
  src/components/Login/Phone.js
  src/components/Login/SignIn.js
  src/components/NavBar/NavBar.js
  src/contexts/GameContext.js
Labels: bug, frontend, feature

#103 Routing auth fix
  src/App.js
  src/components/AuthModal/AuthModal.js
  src/components/BoardSetup/HalfBoard.js
  src/components/BoardSetup/index.js
  src/components/DraggablePiece.js
  src/components/LZQ/BoardBackground.js
  src/components/LZQ/LZQ.js
  src/components/LZQ/MountainPass.js
  src/components/LZQ/index.js
  src/components/NavBar/NavBar.js
  src/components/Position.js
  src/components/Setup/Setup.js
  src/components/Setup/index.js
  src/components/WarnModal/WarnModal.js
  src/components/WarnModal/index.js
  src/contexts/GameContext.js
  src/views/Debug.js
  src/views/Game.js
  src/views/Menu.js
Labels: bug, frontend, feature

#109 Cleanup
  src/api/Game.js
  src/api/User.js
  src/components/BoardSetup/HalfBoard.js
  src/components/BoardSetup/index.js
  src/components/GameOver/GameOver.js
  src/components/Login/CreateAccount.js
  src/components/Login/EmailAndPasswordSignIn.js
  src/components/Login/Phone.js
  src/components/NavBar/NavBar.js
  src/components/UserModal/UserModal.js
  src/contexts/GameContext.js
  src/views/Game.js
  src/views/Menu.js
Labels: documentation

#120 Usability fixes
  package-lock.json
  package.json
  src/App.jsx
  src/components/GameBoard/DeadPieces.jsx
  src/components/GameBoard/FrontLines.jsx
  src/components/GameBoard/Mountain.jsx
  src/components/GameBoard/index.jsx
  src/components/Lobby/Lobby.jsx
  src/components/NavBar/NavBar.jsx
  src/components/Piece/index.jsx
  src/components/Position.jsx
  src/components/WarnModal/WarnModal.jsx
  src/contexts/GameContext.jsx
  src/views/Game.jsx
  src/views/Menu.jsx
Labels: bug, frontend, feature
